In [24]:
import numpy as np
from scipy.sparse.linalg import svds

In [25]:
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

In [26]:
R = R.astype(np.float64)

In [28]:
n_factors = 3
U, Sigma, VT = svds(R, k=n_factors)

In [29]:
print("U (user features):")
U

U (user features):


array([[-0.29627751,  0.66924125,  0.43689593],
       [-0.05015708,  0.44308727,  0.29717498],
       [ 0.54893193, -0.13631518,  0.51589728],
       [ 0.48349385, -0.11077382,  0.39999635],
       [-0.61205501, -0.5700326 ,  0.54282768]])

In [30]:
print("\nSigma (diagonal values):")
Sigma


Sigma (diagonal values):


array([3.77397038, 6.22925557, 9.03171974])

In [31]:
print("\nVT (item features):")
VT


VT (item features):


array([[-0.17212379, -0.25224247, -0.81089006,  0.49920382],
       [ 0.78203025,  0.20891356, -0.45754472, -0.36801718],
       [ 0.47488998,  0.26234348,  0.3005118 ,  0.78444124]])

In [32]:
Sigma = np.diag(Sigma)
R_approx = np.dot(U, np.dot(Sigma, VT))
print("\nReconstructed R:")
R_approx


Reconstructed R:


array([[ 5.32652372,  2.18816428,  0.18504005,  1.00294508],
       [ 3.46567149,  1.32850063, -0.30280243,  0.99518063],
       [ 1.19208569,  0.52241748,  0.10885441,  5.00173251],
       [ 0.86190988,  0.34333338, -0.07825527,  3.9987545 ],
       [-0.05108206,  1.1270053 ,  4.97105194,  3.99953927]])